apiVersion: v1
data:
  slack-api-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4N0RCMDJSMlMvQjA4OEVBMEhBSzEvYU1PUDk0OWg3MGZFTFZvTG9TVHF3Unh3
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
type: Opaque
