apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gift-certificates-pre-prod
  namespace: argocd
spec:
  destination:
    namespace: pre-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gift-certificates
    helm:
      parameters:
        - name: "deployment.container.image"
          value: 'ybuyalskaya/gift-certificates:66'
      valueFiles:
        - values-pre-prod.yaml
    repoURL: https://julie717.github.io/helm-releases/
    targetRevision: 0.0.6
  syncPolicy:
    automated: {}
