apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: argocd
spec:
  destination:
    namespace: ci-cd-helm
    server: https://192.168.203.2:6443
  project: default
  source:
    chart: jenkins-app
    repoURL: https://julie717.github.io/kubernetes/
    targetRevision: 0.1.2
  syncPolicy:
    automated: {}
