apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-app
    repoURL: https://julie717.github.io/kubernetes/
    targetRevision: 0.1.1
  syncPolicy:
    automated: {}
