apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-01-31T21:04:39Z"
  generation: 19
  name: jenkins-app
  namespace: argocd
  resourceVersion: "3165572"
  uid: e9e8af0c-fe62-4ffb-817f-4a32adfd7133
spec:
  destination:
    namespace: ci-cd-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-app
    repoURL: https://julie717.github.io/kubernetes/
    targetRevision: 0.1.0
  syncPolicy:
    automated: {}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2025-01-31T21:05:55Z"
    deployedAt: "2025-01-31T21:05:56Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 0.1.0
    source:
      chart: jenkins-app
      repoURL: https://julie717.github.io/kubernetes/
      targetRevision: 0.1.0
  operationState:
    finishedAt: "2025-01-31T21:05:56Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 0.1.0
    phase: Succeeded
    startedAt: "2025-01-31T21:05:55Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/jenkins-secret created
        name: jenkins-secret
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/basic-security created
        name: basic-security
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/jenkins-tasks-config created
        name: jenkins-tasks-config
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/jenkins-config created
        name: jenkins-config
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/jenkins reconciled.
          reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:default Namespace:ci-cd-helm}. clusterrolebinding.rbac.authorization.k8s.io/jenkins
          configured. Warning: resource clusterrolebindings/jenkins is missing the
          kubectl.kubernetes.io/last-applied-configuration annotation which is required
          by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically."
        name: jenkins
        namespace: ci-cd-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/jenkins created
        name: jenkins
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/jenkins created
        name: jenkins
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/ingress-jenkins created
        name: ingress-jenkins
        namespace: ci-cd-helm
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.1.0
      source:
        chart: jenkins-app
        repoURL: https://julie717.github.io/kubernetes/
        targetRevision: 0.1.0
  reconciledAt: "2025-01-31T21:09:46Z"
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-tasks-config
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - kind: Secret
    name: jenkins-secret
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jenkins
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jenkins
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: ingress-jenkins
    namespace: ci-cd-helm
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://jenkins.k8s-4.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:ybuyalskaya
  sync:
    comparedTo:
      destination:
        namespace: ci-cd-argo
        server: https://kubernetes.default.svc
      source:
        chart: jenkins-app
        repoURL: https://julie717.github.io/kubernetes/
        targetRevision: 0.1.0
    revision: 0.1.0
    status: Synced
